import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { i18n, Locale } from "@/i18n/i18n-config";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale.code }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale }
}>) {
  return (
    <html lang={params.lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Header lang={params.lang} />
          <div className="flex-grow w-full max-w-5xl mx-auto px-2 md:px-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
